# Generated by Django 4.1.3 on 2022-11-02 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendedores', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendedor',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='vendedor',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
