# Generated by Django 4.1.3 on 2022-11-03 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0002_juice_created_at_juice_updated_at'),
        ('pedidos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='produtos',
        ),
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('produto', models.ManyToManyField(to='produtos.juice')),
            ],
        ),
        migrations.AddField(
            model_name='pedido',
            name='items',
            field=models.ManyToManyField(to='pedidos.items'),
        ),
    ]
