# Generated by Django 4.1.3 on 2022-11-03 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0002_juice_created_at_juice_updated_at'),
        ('pedidos', '0002_remove_pedido_produtos_items_pedido_items'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Items',
            new_name='Item',
        ),
    ]
