# Generated by Django 4.1.3 on 2022-11-03 21:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0002_juice_created_at_juice_updated_at'),
        ('pedidos', '0003_rename_items_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='produto',
        ),
        migrations.AddField(
            model_name='item',
            name='produto',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='produtos.juice'),
            preserve_default=False,
        ),
    ]
