# Generated by Django 4.1.3 on 2022-11-04 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0004_remove_item_produto_item_produto'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
