# Generated by Django 4.1.3 on 2022-11-10 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0005_pedido_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='pagamento',
            field=models.BooleanField(default=False),
        ),
    ]
