# Generated by Django 4.1.3 on 2022-11-10 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0006_pedido_pagamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='primeira_compra',
            field=models.BooleanField(default=False),
        ),
    ]
