# Generated by Django 4.1.3 on 2022-11-11 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0007_pedido_primeira_compra'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='recebido',
            field=models.BooleanField(default=False),
        ),
    ]
