# Generated by Django 4.1.3 on 2022-11-15 18:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0010_endereco_ativo'),
        ('pedidos', '0008_pedido_recebido'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='endereco',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='clientes.endereco'),
        ),
    ]
