# Generated by Django 4.1.3 on 2022-11-02 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0003_cliente_created_at_cliente_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='endereco',
            name='apelido',
            field=models.CharField(blank=True, default='Endereço principal', max_length=30),
        ),
    ]
