# Generated by Django 4.1.3 on 2022-11-02 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0007_alter_endereco_uf'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='cpf',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
