# Generated by Django 4.1.3 on 2022-11-04 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vendedores', '0002_vendedor_created_at_vendedor_updated_at'),
        ('clientes', '0008_cliente_cpf'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='vendedor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='vendedores.vendedor'),
            preserve_default=False,
        ),
    ]
