# Generated by Django 4.1.3 on 2022-11-15 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0009_cliente_slug_cliente_vendedor'),
    ]

    operations = [
        migrations.AddField(
            model_name='endereco',
            name='ativo',
            field=models.BooleanField(default=False),
        ),
    ]
