# Generated by Django 4.1.3 on 2022-11-15 19:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0010_endereco_ativo'),
    ]

    operations = [
        migrations.AddField(
            model_name='endereco',
            name='destinatario',
            field=models.CharField(blank=True, default=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.cliente'), max_length=30),
        ),
    ]
