# Generated by Django 4.1.3 on 2022-11-15 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0011_endereco_destinatario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='endereco',
            name='destinatario',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
